### ISSUE TITLE
[feature request] Make LM compatible with Streamlink

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#23]
Hi,

Livestreamer works fine, but it's getting old and plugin issues in particular are not getting fixed.
There is a fork out there called Streamlink which does fix some of these issues. Making it compatible should be relatively painless, since they work basically the same.

Cheers

**Comment by laurencee** [comment]
Heh funny you should mention this, I've recently been looking into this due to the livestreamer problems with higher quality twitch streams.

I'll have to get back into development of this app. 😄 

Besides being able to point at streamlink or livestreamer the next thing I have planned is being able to sync with twitch automatically in both directions.

**Comment by laurencee** [comment]
They just released a new version of streamlink yesterday so I'll see if I can get around to adding support for it tomorrow sometime, along with some basic twitch oauth support.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.9.0

**Comment by Tharn** [comment]
Your turnaround time is _crazy_.
