### ISSUE TITLE
Not recognizing 1080p60/720p60 as best quality

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#30]
Examples

[cli][info] Available streams: 160p (worst), 360p, 480p (best), 720p60, audio_only
[cli][info] Opening stream: 480p (hls)

[cli][info] Available streams: 1080p60, 160p (worst), 360p, 480p, 720p (best), 720p60, audio_only
[cli][info] Opening stream: 720p (hls)

**Comment by laurencee** [comment]
If you're using livestreamer that's a known bug with it's "best" quality option. If you use [streamlink](https://github.com/streamlink/streamlink/releases), that problem is fixed.

Livestreamer was abandoned a while ago and streamlink was forked from livestreamer to continue development of the application.

**Comment by Jakeeeeeeee** [comment]
It's working fine now with streamlink, thanks.

**Comment by laurencee** [comment]
Thanks for closing 👍
