### ISSUE TITLE
Stream unavailable causes quality options to disappear

### ISSUE THREAD

**Issue by GXTX** [laurencee/Livestream.Monitor#32]
When a stream is unavailable on-load up it causes the quality options to disappear and you are then unable to play streams because it's not passing the option off to Streamlink.

https://gfycat.com/deliciouscomposedaustralianfurseal

**Comment by laurencee** [comment]
Nice find (and report), I'll look into sorting that out. 

I presume if you select some other online stream that it'll populate the quality options correctly though?

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.10.1 addresses this

The quality options are intentionally only available for selection when a valid stream is selected since some of the quality options are derived from the currently selected stream.

**Comment by GXTX** [comment]
One issue I can see with the latest commit is while this was happening the settings.json was still reporting the quality to be what I had set it to however I see you are hardcoding the quality to be "best". Shouldn't it default to what ever is in the settings?

**Comment by laurencee** [comment]
Yeah it could do that, an edge case with that approach is that a setting other than best/worst in settings.json may not be available for the selected stream so this approach will always allow the stream to launch.

I can't think of any other situation in which this might happen, it previously happened because a row is selected by default on initializing the application but never fires selection events.
