### ISSUE TITLE
Choosing the best quality problem

### ISSUE THREAD

**Issue by Yersh** [laurencee/Livestream.Monitor#38]
Hi. Recently I found that twitch incorrectly marks the best quality available.
In like 20-30% of streams you see something like:

`[cli][info] Available streams: 160p (worst), 360p, 480p (best), 720p60, audio_only`

To fix this I paste `1080p60,900p60,720p60,Best ` into quality field.
It works, but after restarting Livestream.Monitor it goes back to `Best.`

Can you add a feature for saving custom quality setting for the Livestream.Monitor?

**Comment by laurencee** [comment]
It's already there in the current version (2.11). https://github.com/laurencee/Livestream.Monitor/releases

If you're on 2.11+ did you click save in the bottom right of the stream qualities page before you closed the window?

**Comment by laurencee** [comment]
Ah maybe I misunderstood what you were doing, the quality list is ordered so the entry at the top of the list is the one it'll try first so make sure you order the list from most important at the top to least important at the bottom.

You don't need to put in "Best" or "Worst" at all because that's what the fallback quality option is for. It ensures that if all other options fail that you'll at least have something that should work.

**Comment by laurencee** [comment]
Made a release with some changes thanks to your feedback, let me know if this resolves your issue.

https://github.com/laurencee/Livestream.Monitor/releases/tag/2.11.2

**Comment by Yersh** [comment]
Sorry. I forgot to check for updates before writing.
I was using 2.10.1 version. I updated to 2.11.2 and everything works perfectly. 
Thank you.
