### ISSUE TITLE
Ability to disable refresh stream modal error messages

### ISSUE THREAD

**Issue by Jakeeeeeeee** [laurencee/Livestream.Monitor#49]
Well I suppose we already established there must be an issue on my part (if developer cannot figure the cause then me certainly cannot). Any way to at least disable the error communicates? I have to click a hundred times ok/ignore before it lets me get to the live stream...

https://gyazo.com/6972fe9e98f8892aef5189045c9bb542

https://gyazo.com/7a80a39633ced74bcd559c1510e0e290

**Comment by laurencee** [comment]
Not currently, this would be a new feature. Basically need an "ignore all" button or some setting to disable error messages.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.12.0

**Comment by Jakeeeeeeee** [comment]
I just wanted to say that new release fixed the issue of errors previously reported by me. Can only speculate how but the first thing I've noticed there are no longer displayed the titles of previous stream. Only the live ones have them now? I suppose less queries might have worked at my advantage. Really appreciate the feature for disabling the error dialog but hopefully it wont be needed anymore :)

**Comment by laurencee** [comment]
@Jakeeeeeeee Cheers for the reply, the new twitch api which is now being used throughout the app doesn't return the data for offline streams anymore. 

Overall there are actually more queries required to get the data displayed on screen but each query returns less data than before so that might have something to do with it or it could be the fact it goes to different servers which have better routes for you. I can only guess.

Good to hear that the new api works better for you. Feel free to report any other issues you run into.
