### ISSUE TITLE
Change Page functionality broken

### ISSUE THREAD

**Issue by Tharn** [laurencee/Livestream.Monitor#62]
Making a separate bug report as per request!

Using the Page function, both on VODs, on Top Streams and on Top Streams with Game Filter on, clicking the `<` and `>` buttons will change the Page counter and make the stream list reload without actually changing the stream list. I.e. for all these things, the only page that is accessible is page 1.

**Comment by laurencee** [comment]
It's working now except for top streams that happen to be reruns due to a twitch api bug. This means livestream monitor thinks it's on the last page of data given twitch hasn't returned enough entries to fill a full page so livestream monitor disables the next page button.

The bug manifests when I ask twitch for N top streams, 1 (or more) of them is a rerun so twitch drops it from the response but only returns N-1 streams instead of adding another one that isn't a rerun.

Either twitch should be including the rerun stream in the list returned (makes sense given there's no option in the request to not include/exclude these) or twitch should be including the next highest non-rerun stream to the response.

**Comment by Tharn** [comment]
Cheers. Working fine for Top Streams now.
VOD lists still only display the same single page.

**Comment by laurencee** [comment]
Can try the newest release, should fix that too.

**Comment by Tharn** [comment]
I did, it's all fixed now.

**Comment by laurencee** [comment]
Thanks for updating on this, fixed again. 

Lack of tests on this old project, so I guess I'm offloading the tests to the users, like people did in ages past.

https://github.com/laurencee/Livestream.Monitor/releases/tag/2.16.5
