### ISSUE TITLE
Error launching YouTube chat

### ISSUE THREAD

**Issue by numberneuf** [laurencee/Livestream.Monitor#81]
When launching YouTube chat for a livestream in Firefox Nightly 133.0a.1 on Windows 10, the following error occurs:

> Error launching chat
> Idark_themel is not recognized as an internal or external
> command,
> operable program or batch file.
> lis_popoutl is not recognized as an internal or external
> command,
> operable program or batch file.
> Ifrom_gamingl is not recognized as an internal or external
> command,
> operable program or batch file.

Despite the error, chat does launch in Firefox without issue. I do think this error is different than the one mentioned in the FAQ.

_Aside_ - is this project planned to be updated at all? Last update was nearly a year ago. If not, are there alternatives? I really love this program and would love to see development on it further.

![lm-chat-error](https://github.com/user-attachments/assets/5173cf3a-b4d4-4cbe-bf7a-ce3a1fd39a65)

**Comment by laurencee** [comment]
> When launching YouTube chat for a livestream in Firefox Nightly 133.0a.1 on Windows 10, the following error occurs:
> 
> > Error launching chat
> > Idark_themel is not recognized as an internal or external
> > command,
> > operable program or batch file.
> > lis_popoutl is not recognized as an internal or external
> > command,
> > operable program or batch file.
> > Ifrom_gamingl is not recognized as an internal or external
> > command,
> > operable program or batch file.
> 
> Despite the error, chat does launch in Firefox without issue. I do think this error is different than the one mentioned in the FAQ.
> 

Thanks, looks like the issue is the `&` symbol included in the command line argument to launch chat has to be escaped to `^&` otherwise windows interprets that character as a command separator.

I've applied the change locally and it seems to address this problem.

> _Aside_ - is this project planned to be updated at all? Last update was nearly a year ago. If not, are there alternatives? I really love this program and would love to see development on it further.
> 

I update when stuff breaks (usually important stuff like launching streams), nothing has stopped working in the past year that I am aware of so I've had no need to do any updates to this besides maybe features people have asked for and a nicer way to add youtube streams.

I use this app myself all the time (and is why I wrote it in the first place) so it'll always work for following/launching streams.

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.13.10
